version: ~> 1.0
os: linux
language: ruby
rvm:
- 2.5
script:
- cp config/database.example.yml config/database.yml
- bundle exec rake db:setup RAILS_ENV=test
- bundle exec rails spec
- bundle exec bundle-audit check --update
- bundle exec brakeman -z
after_success:
- echo "branch=$TRAVIS_BRANCH repo=$TRAVIS_REPO_SLUG"
- test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_REPO_SLUG" = "minsk-hackerspace/hackerspace.by" && openssl aes-256-cbc -K $encrypted_622d28529b58_key -iv $encrypted_622d28529b58_iv
  -in deploy_key.enc -out ./deploy_key -d
- test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_REPO_SLUG" = "minsk-hackerspace/hackerspace.by" && eval "$(ssh-agent -s)"
- test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_REPO_SLUG" = "minsk-hackerspace/hackerspace.by" && chmod 600 ./deploy_key
- test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_REPO_SLUG" = "minsk-hackerspace/hackerspace.by" && echo -e "Host hackerspace.by\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_REPO_SLUG" = "minsk-hackerspace/hackerspace.by" && ssh-add ./deploy_key
- test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_REPO_SLUG" = "minsk-hackerspace/hackerspace.by" && ssh -i ./deploy_key mhs@hackerspace.by pwd
- test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_REPO_SLUG" = "minsk-hackerspace/hackerspace.by" && bundle exec mina deploy
