language: ruby
rvm:
- 2.5
script:
- cp config/database.example.yml config/database.yml
- bundle exec rake db:setup RAILS_ENV=test
- bundle exec rails spec
- bundle exec bundle-audit check --update
- bundle exec brakeman -z
after_success:
- openssl aes-256-cbc -K $encrypted_622d28529b58_key -iv $encrypted_622d28529b58_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host hackerspace.by\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key mhs@hackerspace.by pwd
- bundle exec mina deploy
