version: ~> 1.0
os: linux
language: ruby
cache: bundler
rvm:
- 2.7
script:
- cp config/database.example.yml config/database.yml
- bundle exec rake db:setup RAILS_ENV=test
- bundle exec rails spec
- bundle exec bundle-audit check --update
- bundle exec brakeman -z
deploy:
- provider: script
  script: rvm use $TRAVIS_RUBY_VERSION do .cicd/travis_deploy.sh
  on:
    branch: master
