language: ruby
rvm:
- 2.5
script:
- cp config/database.example.yml config/database.yml
- bundle exec rake db:setup RAILS_ENV=test
- bundle exec rails spec
- bundle exec bundle-audit check --update
- bundle exec brakeman -z
after_success:
- test $TRAVIS_BRANCH = "master" && openssl aes-256-cbc -K $encrypted_622d28529b58_key -iv $encrypted_622d28529b58_iv
  -in deploy_key.enc -out ./deploy_key -d
- test $TRAVIS_BRANCH = "master" && eval "$(ssh-agent -s)"
- test $TRAVIS_BRANCH = "master" && chmod 600 ./deploy_key
- test $TRAVIS_BRANCH = "master" && echo -e "Host hackerspace.by\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- test $TRAVIS_BRANCH = "master" && ssh-add ./deploy_key
- test $TRAVIS_BRANCH = "master" && ssh -i ./deploy_key mhs@hackerspace.by pwd
- test $TRAVIS_BRANCH = "master" && bundle exec mina deploy
